// Empty default template file

#ifndef SECUREKEYS_EXTERN_CONSTS_H
#define SECUREKEYS_EXTERN_CONSTS_H

#include <map>
#include <string>

#define SECUREKEYS_HALT_IF_DEBUGGABLE false
#define SECUREKEYS_HALT_IF_EMULATOR false
#define SECUREKEYS_HALT_IF_ADB_ON false
#define SECUREKEYS_HALT_IF_PHONE_NOT_SECURE false
#define SECUREKEYS_INSTALLERS { }
#define SECUREKEYS_SIGNING_CERTIFICATE ""
#define SECUREKEYS_AES_KEY { }
#define SECUREKEYS_AES_INITIAL_VECTOR { }
#define SECUREKEYS_LOAD_MAP(_map) ;

#endif //SECUREKEYS_EXTERN_CONSTS_H
